version: "3"
services:
        hellodocker:
                build:
                   context: .
                   dockerfile: Dockerfile
                ports:
                        - "6060-8080:8080"
                restart: unless-stopped





